<a href="https://colab.research.google.com/github/chaiminwoo0223/Deep-Learning/blob/main/02%20-%20PyTorch_Tensor_Basic_Usage.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1.Tensor

In [1]:
!pip3 install torch torchvision
import torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
# torch.rand() : [0,1)
x = torch.rand(2,3)
print(x)

tensor([[0.4452, 0.6084, 0.2833],
        [0.0587, 0.6351, 0.4233]])


In [3]:
# torch.randn() : 가우시안 정규분포에서 샘플링한 값
# Random Normal
x = torch.randn(2,3)
print(x)

tensor([[ 0.0811, -0.4786, -0.0458],
        [-0.5505, -0.5402,  0.1565]])


In [4]:
# torch.randint() : 시작과 끝 사이의 랜덤한 자연수
# Random Integer
x = torch.randint(2,5,size=(2,3))
print(x)

tensor([[3, 4, 3],
        [4, 4, 4]])


## 2.Zeros & Ones

In [5]:
# torch.zeros() : 0으로 채워진 텐서
x = torch.zeros(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
# 인자로 들어오는 텐서와 형태가 같은 0으로 채워진 텐서
ref = torch.rand(4,5)
x = torch.zeros_like(ref)
print(ref)
print(x)

tensor([[0.2839, 0.4600, 0.5161, 0.4609, 0.0126],
        [0.6960, 0.6374, 0.7559, 0.0932, 0.1655],
        [0.5200, 0.7629, 0.6234, 0.4849, 0.0601],
        [0.9597, 0.4878, 0.2196, 0.0643, 0.8339]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [7]:
# torch.ones() : 1로 채워진 텐서
x = torch.ones(2,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [8]:
# 인자로 들어오는 텐서와 형태가 같은 1로 채워진 텐서
ref = torch.rand(4,5)
x = torch.ones_like(ref)
print(ref)
print(x)

tensor([[0.1485, 0.0377, 0.1133, 0.3609, 0.5489],
        [0.7805, 0.6165, 0.1116, 0.2014, 0.5779],
        [0.1265, 0.3520, 0.8403, 0.2554, 0.3601],
        [0.5947, 0.1408, 0.4642, 0.2129, 0.8386]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


## 3.Tensor Data Type

In [9]:
# tensor.type() : 텐서의 데이터 타입을 리턴
x = torch.rand(2,3)
print(x.type())    # 파이토치에 정의된 메소드
print(type(x))     # 파이썬에 정의된 함수

torch.FloatTensor
<class 'torch.Tensor'>


In [10]:
# tensor.type()을 dtype과 함께 사용하면, 텐서의 데이터 타입을 dtype에 넣어준 데이터 타입으로 변환
double_x = x.type(dtype=torch.DoubleTensor)
print(double_x.type())

torch.DoubleTensor


In [11]:
# tensor.type_as() : 텐서의 데이터 타입을 변환
int_x = x.type_as(torch.IntTensor())
print(int_x.type())

torch.IntTensor


## 4.Numpy to Tensor & Tensor to Numpy

In [12]:
import numpy as np

In [13]:
# torch.from_numpy(ndarray) : 넘파이 배열을 토치 텐서로 변환
x1 = np.ndarray(shape=(2,3), dtype=int,buffer=np.array([1,2,3,4,5,6]))
x2 = torch.from_numpy(x1)
print(x1)
print(x2, x2.type())

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]]) torch.LongTensor


In [14]:
# tensor.numpy() : 토치 텐서를 넘파이 배열로 변환
x3 = x2.numpy()
print(x2)
print(x3)

tensor([[1, 2, 3],
        [4, 5, 6]])
[[1 2 3]
 [4 5 6]]


## 5.Tensor on CPU & GPU

In [15]:
# 배열을 인자로 넣어 토치 텐서를 생성
x = torch.FloatTensor([[1,2,3],[4,5,6]])
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [16]:
# device 함수를 사용해, 텐서를 원하는 장치로 이동
cpu = torch.device('cpu')
gpu = torch.device('cuda')

In [17]:
# gpu가 사용 가능한지 체크
# .to 함수를 이용해, 지정한 장치로 이동
if torch.cuda.is_available():
  x_gpu = x.to(gpu)
  print(x_gpu)
  
x_cpu = x_gpu.to(cpu)
print(x_cpu)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [18]:
# tensor.size() : 텐서의 형태를 확인

# 대괄호 없음 = 사이즈를 지정
x = torch.FloatTensor(10,12,3,3)
print(x.size(), x.size()[1:2], sep="\n")
# 대괄호 있음 = 값을 지정
x = torch.FloatTensor([10,12,3,3])
print(x.size(), x.size()[0], sep="\n")

torch.Size([10, 12, 3, 3])
torch.Size([12])
torch.Size([4])
4


## 6.Indexing, Joining, Slicing & Squeezing

In [19]:
# Indexing
x = torch.randn(4,3)
print(x)
print(x[1:3])

tensor([[ 0.7616,  1.2821,  1.3537],
        [ 1.3621, -0.1960,  0.1767],
        [-0.7791,  0.1326,  1.3418],
        [ 1.1299, -1.2716,  0.1481]])
tensor([[ 1.3621, -0.1960,  0.1767],
        [-0.7791,  0.1326,  1.3418]])


In [20]:
# torch.index_select() : 지정한 차원 기준으로 원하는 값들을 선택할 수 있음
selected = torch.index_select(x,dim=1,index=torch.LongTensor([0,2]))
print(x)
print(selected)

tensor([[ 0.7616,  1.2821,  1.3537],
        [ 1.3621, -0.1960,  0.1767],
        [-0.7791,  0.1326,  1.3418],
        [ 1.1299, -1.2716,  0.1481]])
tensor([[ 0.7616,  1.3537],
        [ 1.3621,  0.1767],
        [-0.7791,  1.3418],
        [ 1.1299,  0.1481]])


In [21]:
# torch.masked_select(input, mask) : 뽑고자 하는 값들을 마스킹해서 선택할 수 있음
x = torch.randn(2,3)
mask = torch.ByteTensor([[0,0,1],[0,1,0]])
out = torch.masked_select(x,mask)
print(x, mask, out, sep="\n\n")

tensor([[ 1.4241,  1.5851, -0.1880],
        [ 0.6320, -0.0287,  0.2919]])

tensor([[0, 0, 1],
        [0, 1, 0]], dtype=torch.uint8)

tensor([-0.1880, -0.0287])


<ipython-input-21-1b7d35e77d78>:4: UserWarning: masked_select received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (Triggered internally at ../aten/src/ATen/native/TensorAdvancedIndexing.cpp:1729.)
  out = torch.masked_select(x,mask)


In [22]:
# torch.cat(seq, dim=0) : 텐서를 원하는대로 붙일 수 있음
x = torch.FloatTensor([[1,2,3],[4,5,6]])       # 2*3
y = torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]]) # 2*3
z1 = torch.cat([x,y],dim=0)                    # 4*3
z2 = torch.cat([x,y],dim=1)                    # 2*6
print(x,y,z1,z2,sep="\n\n")

tensor([[1., 2., 3.],
        [4., 5., 6.]])

tensor([[-1., -2., -3.],
        [-4., -5., -6.]])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])

tensor([[ 1.,  2.,  3., -1., -2., -3.],
        [ 4.,  5.,  6., -4., -5., -6.]])


In [23]:
# torch.stack(seq, dim=0) : 텐서를 원하는대로 붙일 수 있음(차원 확장)
x = torch.FloatTensor([[1,2,3],[4,5,6]]) # 2*3
x_stack = torch.stack([x,x,x,x],dim=0)   # 4*2*3
print(x_stack,x_stack.size(),sep="\n\n")

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]])

torch.Size([4, 2, 3])


In [24]:
# torch.chunk(tensor, chunks, dim=0) : 텐서를 원하는 chunk 개수만큼 분리할 수 있음
x_1, x_2 = torch.chunk(z1,2,dim=0)
y_1, y_2, y_3 = torch.chunk(z1,3,dim=1)
print(z1,x_1,x_2,z1,y_1,y_2,y_3,sep="\n\n")

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])

tensor([[1., 2., 3.],
        [4., 5., 6.]])

tensor([[-1., -2., -3.],
        [-4., -5., -6.]])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])

tensor([[ 1.],
        [ 4.],
        [-1.],
        [-4.]])

tensor([[ 2.],
        [ 5.],
        [-2.],
        [-5.]])

tensor([[ 3.],
        [ 6.],
        [-3.],
        [-6.]])


In [25]:
# torch.split(tensor, split_size, dim=0) : 원하는 사이즈로 텐서를 자를 수 있음
x1,x2 = torch.split(z1,2,dim=0)
y1 = torch.split(z1,2,dim=1) 
print(z1,x1,x2,sep="\n\n")
print("This is y1:")
for i in y1:
  print(i)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])

tensor([[1., 2., 3.],
        [4., 5., 6.]])

tensor([[-1., -2., -3.],
        [-4., -5., -6.]])
This is y1:
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [-1., -2.],
        [-4., -5.]])
tensor([[ 3.],
        [ 6.],
        [-3.],
        [-6.]])


In [26]:
# torch.squeeze(input, dim=None) : 길이가 1인 차원들을 압축시킬 수 있음
x1 = torch.FloatTensor(10,1,3,1,4)
x2 = torch.squeeze(x1)
print(x1.size(),x2.size(),sep="\n")

torch.Size([10, 1, 3, 1, 4])
torch.Size([10, 3, 4])


In [27]:
# torch.unsqueeze(input, dim=None) 차원을 늘릴수 있음
x1 = torch.FloatTensor(10,3,4)
x2 = torch.unsqueeze(x1,dim=0)
print(x1.size(),x2.size(),sep="\n")

torch.Size([10, 3, 4])
torch.Size([1, 10, 3, 4])


## 7.Initialization

In [28]:
import torch.nn.init as init

In [29]:
# uniform 분포를 따라 텐서를 초기화 할 수 있음
x1 = init.uniform_(torch.FloatTensor(3,4),a=0,b=9)
# 정규 분포를 따라 텐서를 초기화 할 수 있음
x2 = init.normal_(torch.FloatTensor(3,4),std=0.2)
# 지정한 값으로 텐서를 초기화 할 수 있음
x3 = init.constant_(torch.FloatTensor(3,4),3.1415)
print(x1,x2,x3,sep="\n")

tensor([[8.6907, 5.6352, 1.0886, 5.5619],
        [1.5300, 1.8654, 0.6595, 1.4503],
        [1.6187, 8.5029, 8.1024, 2.8617]])
tensor([[ 0.1816,  0.0651,  0.2105,  0.0208],
        [ 0.2151,  0.2145,  0.0855, -0.1102],
        [-0.3916, -0.4010, -0.2592, -0.1650]])
tensor([[3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415]])


## 8.Math Operations

In [30]:
# torch.add(): 더하기 연산
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
add = torch.add(x1,x2)
print(x1,x2,add,x1+x2,sep="\n")

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [31]:
# torch.add() -> broadcasting
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.add(x1,10)
print(x1,x2,x1+10,sep="\n")

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[11., 12., 13.],
        [14., 15., 16.]])
tensor([[11., 12., 13.],
        [14., 15., 16.]])


In [32]:
# torch.sub(): 빼기 연산
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
sub = torch.sub(x1,x2)
print(x1,x2,sub,x1-x2,sep="\n")

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [33]:
# torch.sub() -> broadcasting
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.sub(x1,10)
print(x1,x2,x1-10,sep="\n")

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[-9., -8., -7.],
        [-6., -5., -4.]])
tensor([[-9., -8., -7.],
        [-6., -5., -4.]])


In [34]:
# torch.mul() : 곱하기 연산(사이즈 일치)
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.mul(x1,x2)
print(x3)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])


In [35]:
# torch.mul() -> broadcasting
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.mul(x1,10)
print(x1,x2,x1*10,sep="\n")

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[10., 20., 30.],
        [40., 50., 60.]])
tensor([[10., 20., 30.],
        [40., 50., 60.]])


In [36]:
# torch.div() : 나누기 연산(사이즈 일치)
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.div(x1,x2)
print(x3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [37]:
# torch.div() -> broadcasting
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.div(x1,10)
print(x1,x2,x1/10,sep="\n")

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000]])
tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000]])


In [38]:
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
# torch.pow(input,exponent) : 파워 연산(x의 n승)
x2 = torch.pow(x1,2)
# torch.exp(tensor,out=None) : exponential 연산
x3 = torch.exp(x1)
# torch.log(input,out=None) : 로그 연산
x4 = torch.log(x1)
print(x1,x2,x3,x4,sep="\n")

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])
tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])


## 9.Matrix Operations

In [39]:
# torch.mm(mat1,mat2) : 행렬곱 연산
x1 = torch.FloatTensor(3,4)
x2 = torch.FloatTensor(4,5)
torch.mm(x1,x2).size()

torch.Size([3, 5])

In [40]:
# torch.bmm(batch1,batch2) : 배치 행렬곱 연산
x1 = torch.FloatTensor(10,3,4)
x2 = torch.FloatTensor(10,4,5)
torch.bmm(x1,x2).size()

torch.Size([10, 3, 5])

In [41]:
# torch.dot(tensor1,tensor2) : 내적 연산
x1 = torch.tensor([2, 3])
x2 = torch.tensor([2, 1])
torch.dot(x1,x2)

tensor(7)

In [42]:
# torch.t(matrix) : 행렬의 전치
x1 = torch.tensor([[1,2],[3,4]])
print(x1,x1.t(),sep="\n")

tensor([[1, 2],
        [3, 4]])
tensor([[1, 3],
        [2, 4]])


In [43]:
# torch.transpose(input,dim0,dim1) : 차원을 지정할 수 있는 행렬의 전치 연산
x1 = torch.FloatTensor(10,3,4)
print("1번 차원과 2번 차원을 전치")
print(x1.size(), torch.transpose(x1,1,2).size(), x1.transpose(1,2).size(),sep="\n")
print("\n0번 차원과 2번 차원을 전치")
print(x1.size(), torch.transpose(x1,0,2).size(), x1.transpose(0,2).size(),sep="\n")

1번 차원과 2번 차원을 전치
torch.Size([10, 3, 4])
torch.Size([10, 4, 3])
torch.Size([10, 4, 3])

0번 차원과 2번 차원을 전치
torch.Size([10, 3, 4])
torch.Size([4, 3, 10])
torch.Size([4, 3, 10])
