<a href="https://colab.research.google.com/github/chaiminwoo0223/Deep-Learning/blob/main/03%20-%20Gradient_Calculation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install torch torchvision

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np
import torch

## 1.기울기 계산 기능(Gradient Calculation Requirement)

In [3]:
# 텐서의 기울기 게산 : requires_grad=True
x = torch.tensor([1.,2.,3.], requires_grad=True)
y = torch.tensor([2.,3.,4.], requires_grad=True)
# [1.,2.,3.] + [2.,3.,4.] = [3.,5.,7.]
z = x + y
# 기울기 계산 여부
print(x, x.requires_grad)
print(y, y.requires_grad)
print(z, z.requires_grad)

tensor([1., 2., 3.], requires_grad=True) True
tensor([2., 3., 4.], requires_grad=True) True
tensor([3., 5., 7.], grad_fn=<AddBackward0>) True


In [4]:
# backward() : 연산 그래프를 쭉 따라가면서, leaf node에 대한 기울기를 계산
a = z.sum().backward()
print(a)

None


## 2.인퍼런스 모드(Inference Mode)

- 학습이 이루어진 상황에서 모델의 결과값만 보고 싶을때 사용

In [5]:
# torch.no_grad() : 기울기 계산을 끌 수 있음
# 파이썬 문법인 with 를 사용해, 해당 부분만 기울기 계산을 끔(모델을 인퍼런스 모드로 사용)
with torch.no_grad():
    z = x + y
    
print(x.requires_grad, y.requires_grad)
print(z.requires_grad)

True True
False


## 3.텐서의 위치 할당 (Device Allocation of Tensor)

In [6]:
# device 함수를 사용해, 텐서를 원하는 장치로 이동
cpu = torch.device('cpu')
gpu = torch.device('cuda')
# 텐서를 생성할 때, 장치를 지정
x = torch.tensor([1.,2.,3.], dtype=torch.float64, device=cpu, requires_grad=True)
print(x.device)
# .to 함수를 이용해, cpu에 만들어진 텐서를 gpu로 이동
if torch.cuda.is_available():
    x = x.to(gpu)
    print(x.device)

cpu
cuda:0


## 4.기울기 계산(Gradient Calculation)
- z = 2x^2+3

In [7]:
# z = 2x^2+3
x = torch.tensor(data=[2.0,3.0],requires_grad=True)
y = x**2
z = 2*y +3
# 기울기 계산 여부
print(x, x.requires_grad)
print(y, y.requires_grad)
print(z, z.requires_grad)

tensor([2., 3.], requires_grad=True) True
tensor([4., 9.], grad_fn=<PowBackward0>) True
tensor([11., 21.], grad_fn=<AddBackward0>) True


In [8]:
# 목표값을 지정
target = torch.tensor([3.0,4.0])
# z와 목표값의 절대값 차이를 계산
loss = torch.sum(torch.abs(z-target))
# 스칼라 값이 된 loss에 대해, backward()를 적용
loss.backward()
# x,y,z 중 x만이 leaf node이기 때문에, y와 z는 기울기가 None으로 나옴
print(x.grad, y.grad, z.grad)

tensor([ 8., 12.]) None None


<ipython-input-8-30062eb013e5>:8: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:480.)
  print(x.grad, y.grad, z.grad)
